config/routes.rb
Rails.application.routes.draw do
  get 'bollywoods/index'

  get 'bollywoods/new'

  get 'bollywoods/create'

  get 'bollywoods/destroy'
  resources :bollywoods, only: [:index, :new, :create, :destroy]   
   root "bollywoods#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bollywood.rb
class Bollywood < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :category, :year, :price, :attachment, presence: true # Make sure the owner's name is present.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bollywoods_controller.rb
class BollywoodsController < ApplicationController
  def index   
    @bollywoods = Bollywood.all   
 end   
    
 def new   
    @bollywood = Bollywood.new   
 end   
    
 def create   
    @bollywood = Bollywood.new(bollywood_params)   
       
    if @bollywood.save   
       redirect_to bollywoods_path, notice: "Successfully uploaded."   
    else   
       render "new"   
    end   
       
 end   
    
 def destroy   
    @bollywood = Bollywood.find(params[:id])   
    @bollywood.destroy   
    redirect_to bollywoods_path, notice:  "Successfully deleted."   
 end   
    
 private   
    def bollywood_params   
    params.require(:bollywood).permit(:title, :category, :year, :price, :attachment)   
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bollywoods_helper.rb
module BollywoodsHelper
end

app/views/bollywoods/create.html.erb
<h1>Bollywoods#create</h1>
<p>Find me in app/views/bollywoods/create.html.erb</p>

app/views/bollywoods/destroy.html.erb
<h1>Bollywoods#destroy</h1>
<p>Find me in app/views/bollywoods/destroy.html.erb</p>

app/views/bollywoods/index.html.erb
<style>
h1{
  text-align:center;
  color:white;
  background:blue;
}
h2{
    
    color:black;
    font-family:"Baskerville Old Face";
    font-size:22px;
    text-decoration:none;
    text-shadow:1px 1px 0px white;  
    margin:20px;
    display: inline-block;
}
.card-img-top{
  height:200px;
  weight:100px;
}
footer{
  background: black;
  padding:15px;
}
footer p{
  text-align:center;
  color:white;
}
</style>
<br>

<center>
<h2><td><a href="">Home</a><a href="">Movie </a><a href="">Hobbie</a><a href="">Contact</a>
<input type="text" style="width:260px;"/><input type="submit" value="search"/></p>
</td>
</tr>
</h2>
<center>
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  <h1><b>Jorah Indian Movie Company Ltd<b></h1>  
  
<center><b><u><h4><%= link_to "New Bollywood", new_bollywood_path %></h4></u></b></center>   
<br>   
<br>   
    

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      <% @bollywoods.each do |bollywood| %> 
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img src="<%= bollywood.attachment %>" class="card-img-top" alt="card img cap"> 
      
            <div class="card-body">
              <p class="card-text"><b>Title:</b><%= bollywood.title %><br><b>category:</b><%= bollywood.category %><br><b>Year:</b><%= bollywood.year %><br><b>Price:</b><%= bollywood.price %></p>
             <b><u><%= link_to "Download", bollywood.attachment_url %></u></b>
               <b><u><%= link_to "Delete",  bollywood, method: :delete, confirm: "Are you sure you want to delete #{bollywood.attachment}?" %></u></b>
              </div>
            </div>
          </div>
              <% end %>   
        </div>
        <br>
        <br>
    
<footer class="text-muted">
  <div class="container">
    <p class="float-right"> </p>
    <p><b> INFORMATION TECHNOLOGY @ 2019</b> </p>
    <p>@right and Designed by Jackson HAKIZIMANA @ 2019 </p>

  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>

app/views/bollywoods/new.html.erb
   <br>
   <br>
   <center>
<%= form_for @bollywood, html: { multipart: true } do |f| %>   
    <%= f.label :title %>   
    <%= f.text_field :title %> 
    <br><br>
     <%= f.label :category %>   
    <%= f.text_field :category %>
    <br><br>
    <%= f.label :year %>   
    <%= f.text_field :year %>
    <br><br>
    <%= f.label :price %>   
    <%= f.text_field :price %>  
    <br><br>   
    <%= f.label :attachment %>   
    <%= f.file_field :attachment %>   
    <br>   
    <%= f.submit "Save",class: "btn btn-primary" %>   
 <% end %> 
 </center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>   
 <head>   
      <title>Zuma Indian Movie Uploading</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>   
      
   <body>   
      <div>   
         <%= yield %>   
      </div>   
   </body>   
</html>